[workspace]
members = ["tss2-tcti", "tss2-tcti-sys", "tss2-tcti-foobar", "tpm2-tcti-rm", "tpm2-types", "tpm2-types-alg"]
resolver = "2"

[patch.crates-io]
serde = { git = 'https://github.com/lg3696/serde' }
