[package]
name = "serde_tpm2"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
log = "0.4.20"
paste = "1.0.14"
serde = { version = "1.0.152", features = ["derive"], git = "https://github.com/LG3696/serde.git" }
