[package]
name = "tpm2-types-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.75"
quote = "1.0.35"
syn = {version = "2.0.46", features = ["full", "extra-traits"]}
